yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

urlpatterns = [
    path("about/", include("about.urls", namespace="about")),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls)
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/comments.html
{% load user_filters %}
{% for comment in comments %}
<div class="media mb-4">
  <div class="media-body">
    <h6 class="mt-0">
      <b>
      Пользователь:</b>
      <a href="{% url 'posts:profile' comment.author.username %}">
      {{ comment.author.username }}
      </a>
      
    </h5>
    <b>Оставил комментарий:</b>
      <p>
       {{ comment.text }}
      </p>
    </div>
  </div>
{% endfor %} 

{% if user.is_authenticated %}
<div class="card my-4">
<h7 class="card-header">Добавить комментарий:</h7>
<div class="card-body">
<form method="post" action="{% url 'posts:add_comment' post.id %}">
  {% csrf_token %}      
  <div class="form-group mb-2">
    {{ form.text|addclass:"form-control" }}
  </div>
  <button type="submit" class="btn btn-primary">Отправить</button>
</form>
</div>
</div>
{% endif %} 

yatube/templates/includes/footer.html
<p>© {% now "Y" %} Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <span style="color:red">Ya</span>tube
    </a>
    {# Добавлено в спринте #}

    {% comment %}
    Меню - список пунктов со стандартными классами Bootsrap.
    Класс nav-pills нужен для выделения активных пунктов
    {% endcomment %}
    
    <ul class="nav nav-pills">
      {% with request.resolver_match.view_name as view_name %}
      <li class="nav-item">
        <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" href="{% url 'about:author' %}">Об
          авторе</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}"
          href="{% url 'about:tech' %}">Технологии</a>
      </li>
      {% comment %} Проверка на аудентификацию {% endcomment %}
      {% if request.user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}"
          href="{% url 'posts:post_create' %}">Новая запись</a>
      </li>
      <li class="nav-item">
        <a class="nav-link link-light {% if view_name  == 'users:password_change_form' %}active{% endif %}"
          href="{% url 'users:password_change_form' %}">Изменить пароль</a>
      </li>
      <li class="nav-item">
        <a class="nav-link link-light {% if view_name  == 'users:logout' %}active{% endif %}"
          href="{% url 'users:logout' %}">Выйти</a>
      </li>
      <li>
        Пользователь: {{ user.username }}
      <li>
        {% else %}
      <li class="nav-item">
        <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}"
          href="{% url 'users:login' %}">Войти</a>
      </li>
      <li class="nav-item">
        <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}"
          href="{% url 'users:signup' %}">Регистрация</a>
      </li>
      {% endif %}
      {% endwith %}
    </ul>
    {# Конец добавленого в спринте #}
  </div>
</nav>

yatube/templates/includes/post_pattern.html
{% load thumbnail %}
<article>
<ul>
  <li>
    Автор: {{ post.author.get_full_name }}
    {% if post.author and not author %}
    <a href={% url 'posts:profile' post.author %}>все записи пользователя</a>
    {% endif %}
  </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
  <img class="card-img my-2" src="{{ im.url }}">
{% endthumbnail %}    
  <p>
    {{ post.text }}
  </p>
  <a href="{% url 'posts:post_detail' post.pk  %}">подробная информация</a>
  <br>
  {% if post.group and not group %}
  <a href="{% url 'posts:group_list' post.group.slug %}">все записи сообщества</a>
  {% endif %}
  {% if not forloop.last %}
  <hr>
  {% endif %} 
</article>