yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

urlpatterns = [
    path("about/", include("about.urls", namespace="about")),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls)
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

from core.models import CreatedModel

User = get_user_model()


class Group(models.Model):

    title = models.CharField(max_length=200)
    description = models.TextField()
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self) -> str:
        return self.title


class Post(models.Model):

    text = models.TextField(
        'Текст поста'
    )
    pub_date = models.DateTimeField('Дата публикации', auto_now_add=True)
    author = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='posts',
    )

    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name='Группа',
        related_name='groups',
    )

    image = models.ImageField(
        'Изображение',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(CreatedModel):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария'
    )
    text = models.TextField(
        'Текст комментария',
    )

    class Meta:
        ordering = ['created']
        verbose_name = 'Комментарии'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор'
    )

yatube/posts/forms.py
from django.forms import ModelForm

from .models import Post, Comment


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['text', 'group', 'image']
        labels = {
            'group': 'Группа',
            'text': 'Текст',
        }
        help_texts = {
            'group': 'Вы можете выбрать раздел сообщества, '
            'к которому будет принадлежать эта запись.',
            'text': 'Обязательное поле.',
            'image': 'Выберите изображение для загрузки.',
        }


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        labels = {'text': 'Текст'}

yatube/posts/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.conf import settings

from .forms import PostForm, CommentForm
from .models import Post, Group, User, Follow

User = get_user_model()


def paginator(request, object_list, per_page):
    paginate = Paginator(object_list, per_page)
    page_number = request.GET.get('page')
    page_obj = paginate.get_page(page_number)
    return page_obj


def index(request):
    posts = Post.objects.select_related('author', 'group')
    page_obj = paginator(request, posts, settings.SORT_POSTS)
    template = 'posts/index.html'
    context = {
        'posts': posts,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.groups.select_related('author')
    page_obj = paginator(request, posts, settings.SORT_POSTS)
    template = 'posts/group_list.html'
    context = {
        'group': group,
        'posts': posts,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.select_related('group')
    count = posts.count()
    following = request.user.is_authenticated and Follow.objects.filter(
        user=request.user,
        author=author
    )
    page_obj = paginator(request, posts, settings.SORT_POSTS)
    context = {
        'page_obj': page_obj,
        'count': count,
        'author': author,
        'following': following,
    }

    template = 'posts/profile.html'

    return render(request, template, context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post_title = post.text[:30]
    form = CommentForm(request.POST or None)
    author = post.author
    author_posts = author.posts.all().count()
    comments = post.comments.select_related('author')
    context = {
        'post': post,
        'post_title': post_title,
        'author': author,
        'author_posts': author_posts,
        'form': form,
        'comments': comments,
    }

    template = 'posts/post_detail.html'

    return render(request, template, context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', request.user)
    template = 'posts/create_post.html'
    context = {'form': form}
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)
    if form.is_valid():
        edited_post = form.save()
        edited_post.save()
        return redirect('posts:post_detail', post_id)
    context = {
        'form': form,
        'is_edit': True,
        'post': post,
    }
    template = 'posts/create_post.html'
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    page_obj = paginator(request, post_list, settings.SORT_POSTS)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
{% if is_edit %}
  Редактировать запись
{% else %}
  Новая запись
{% endif %}
{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %}
              Редактировать запись
            {% else %}
              Новая запись
            {% endif %}
          </div>
          <div class="card-body">

            <form
              method="post"
              enctype="multipart/form-data"
            >

              {% csrf_token %}
              {% for field in form %}
                <div class="form-group row my-3 p-3">
                  {% if not field.is_hidden and not nolabel %}
                    <label for="{{ field.id_for_label }}">
                      {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                    </label>
                  {% endif %}
                  {% if field.errors %}
                    {{ field|addclass:'form-control is-invalid' }}
                  {% elif form.is_bound %}
                    {{ field|addclass:"form-control is-valid" }}
                  {% else %}
                    {{ field|addclass:'form-control' }}
                  {% endif %}
                  {% if field.help_text %}
                    <small id="{{field.id_for_label}}-help"
                      class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div> 
  </div> 
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}Подписки{% endblock %}
{% block content %}
{% load cache %}
  <div class="container py-5">
    <h1>Избранные авторы</h1>
    {% include 'posts/includes/switcher.html' with follow=True %}
    {% include 'posts/includes/paginator.html' %}
    {% for post in page_obj %}
      {% include 'posts/includes/favourites.html' %}
      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">
          все записи группы {{ post.group.title }}
        </a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}{{ group.title }}{% endblock %}
{% block header %}{{ group.title }}{% endblock %}
{% block content %}
 <p> {{ group.description }} </p>
{% for post in page_obj %}
  {% include 'includes/post_pattern.html'%} 
{% endfor %} 
{% include 'posts/includes/paginator.html' %}
</div>  
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
Главная страница Yatube
{% endblock title %}
{% block content %}
<div class="container">     
 <h2>Последние обновления на сайте</h2>
 {% include 'posts/includes/switcher.html' %}
{% for post in page_obj %}
  {% include 'includes/post_pattern.html'%}
{% endfor %} 
{% include 'posts/includes/paginator.html' %}
</div>  
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Пост {{ post_title }}{% endblock %}
{% block header %}
<h6> Информация о публикации: {{ post_title }} </h6>
{% endblock %}
{% block content %}
     <div class="row">
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li>
            {% if post.group %}   
              <li class="list-group-item">
                Группа: {{ post.group.title }}
                <a href="{% url 'posts:group_list' post.group.slug %}">
                  все записи сообщества
                </a>
              </li>
            {% endif %}
              <li class="list-group-item">
                Автор: {{ post.author.get_full_name }} {{ author }}
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ author_posts }}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author %}">
                все записи пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          <p>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
            {{ post.text }}
            <br>
            {% if user == post.author %}
            <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}"> 
              редактировать запись 
            </a>
            {% endif %}
            <hr>
          {% include 'includes/comments.html'%} 
          </p>
        </article>
      </div>
      {% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Профайл пользователя {{ author }}{% endblock %}
{% block content %}
    <h2>Все записи пользователя: {{ author.get_full_name }}</h2>
    <h4>Всего постов: {{ count }} </h4>
    {% if user.is_authenticated and user != author %}
    {% if following %}
      <a
        class="btn btn-lg btn-light"
        href="{% url 'posts:profile_unfollow' author.username %}"
        role="button"
      >
        Отписаться
      </a>
    {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}"
          role="button"
        >
          Подписаться
        </a>
    {% endif %}
  {% endif %}
    {% for post in page_obj %}
    {% include 'includes/post_pattern.html'%} 
  {% endfor %}
    {% include 'posts/includes/paginator.html' %}
{% endblock %}